'use client'

import { useEffect, useState } from 'react'
import {
  Megaphone, Sparkles, RefreshCw, AlertTriangle, Download,
  ChevronDown, ChevronRight, Inbox, Wand2, Copy, Check,
} from 'lucide-react'
import {
  api,
  type MarketingPlanRecord, type MarketingGenerateRequest,
  type MonthlyBudget, type WprecoverPlan, type ProjectSummary,
  type ContentPiece, type Ticket, type Prioridad, type WhatsAppMessage,
} from '@/lib/api'

const BUDGET_LABELS: Record<MonthlyBudget, string> = {
  bajo: 'Bajo', medio: 'Medio', alto: 'Alto',
}
const PLAN_LABELS: Record<WprecoverPlan, string> = {
  starter: 'Starter', growth: 'Growth', scale: 'Scale', elite: 'Elite',
}
const PRIO_CLS: Record<Prioridad, string> = {
  Critica: 'badge-critica', Alta: 'badge-alta', Media: 'badge-media', Baja: 'badge-baja',
}

// ---------------------------------------------------------------------------
// Collapsible section
// ---------------------------------------------------------------------------
function Section({
  title, defaultOpen = false, children,
}: { title: string; defaultOpen?: boolean; children: React.ReactNode }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="border border-border rounded-xl overflow-hidden">
      <button
        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-s2 transition-colors text-left"
        onClick={() => setOpen(o => !o)}
      >
        {open ? <ChevronDown className="w-4 h-4 text-muted" /> : <ChevronRight className="w-4 h-4 text-muted" />}
        <span className="font-medium text-sm flex-1">{title}</span>
      </button>
      {open && (
        <div className="border-t border-border bg-s2 px-4 py-4">
          {children}
        </div>
      )}
    </div>
  )
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ol className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2.5 text-sm text-dim">
          <span className="flex-shrink-0 w-5 h-5 rounded-full bg-s3 text-xs font-mono
                           flex items-center justify-center text-muted">{i + 1}</span>
          <span>{item}</span>
        </li>
      ))}
    </ol>
  )
}

// ---------------------------------------------------------------------------
// Content piece card — generated by ContentAgent, with copy button
// ---------------------------------------------------------------------------
function ContentPieceCard({ piece }: { piece: ContentPiece }) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(piece.texto_completo)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard API unavailable (e.g. insecure context) — user can still select+copy manually.
    }
  }

  return (
    <div className="bg-surface border border-border rounded-lg p-3 space-y-2">
      <div className="flex items-center gap-2">
        <span className="text-xs font-mono text-accent">Día {piece.dia}</span>
        <span className="text-[10px] text-muted bg-s3 rounded px-1.5 py-0.5">{piece.formato}</span>
        <span className="text-xs text-dim font-medium ml-1 flex-1">{piece.objetivo}</span>
      </div>

      <p className="text-sm text-dim whitespace-pre-wrap">{piece.texto_completo}</p>

      <div className="flex flex-wrap gap-1">
        {piece.hashtags.map((tag, i) => (
          <span key={i} className="text-[10px] text-accent bg-accent/10 rounded px-1.5 py-0.5">{tag}</span>
        ))}
      </div>

      <p className="text-xs text-muted italic">Prompt de imagen: {piece.prompt_imagen}</p>
      <p className="text-xs text-muted">Mejor horario para publicar: <span className="text-dim">{piece.mejor_horario}</span></p>

      <button
        className="btn-ghost border border-border flex items-center gap-1.5 text-xs"
        onClick={copy}
      >
        {copied
          ? <><Check className="w-3.5 h-3.5 text-success" /> Copiado</>
          : <><Copy className="w-3.5 h-3.5" /> Copiar texto</>}
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// WhatsApp message card — generated by WhatsAppAgent, with copy button
// ---------------------------------------------------------------------------
function WhatsAppMessageCard({ message }: { message: WhatsAppMessage }) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(message.mensaje_texto)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard API unavailable (e.g. insecure context) — user can still select+copy manually.
    }
  }

  return (
    <div className="bg-surface border border-border rounded-lg p-3 space-y-2">
      <span className="text-xs font-mono text-accent">{message.categoria}</span>

      <p className="text-sm text-dim whitespace-pre-wrap">{message.mensaje_texto}</p>

      <div className="flex flex-wrap gap-1">
        {message.variables_sugeridas.map((v, i) => (
          <span key={i} className="text-[10px] text-accent bg-accent/10 rounded px-1.5 py-0.5">{v}</span>
        ))}
      </div>

      <p className="text-xs text-muted">
        Mejor momento de envío: <span className="text-dim">{message.mejor_momento_envio}</span>
      </p>

      <button
        className="btn-ghost border border-border flex items-center gap-1.5 text-xs"
        onClick={copy}
      >
        {copied
          ? <><Check className="w-3.5 h-3.5 text-success" /> Copiado</>
          : <><Copy className="w-3.5 h-3.5" /> Copiar texto</>}
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Action ticket row — created by execute-actions (Módulo 9)
// ---------------------------------------------------------------------------
function ActionTicketRow({ ticket }: { ticket: Ticket }) {
  return (
    <div className="bg-surface border border-border rounded-lg p-3 flex items-start gap-3">
      <span className={`${PRIO_CLS[ticket.prioridad]} flex-shrink-0`}>{ticket.prioridad}</span>
      <div className="flex-1 min-w-0">
        <p className="text-sm text-dim">{ticket.titulo}</p>
        <p className="text-[10px] text-muted font-mono mt-1">
          {ticket.id} · Ticket creado · {ticket.estimacion}m est.
        </p>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Plan display — 9 modules
// ---------------------------------------------------------------------------
function PlanSections({ plan, planId }: { plan: MarketingPlanRecord['plan']; planId: string }) {
  const [pieces, setPieces] = useState<ContentPiece[] | null>(null)
  const [executing, setExecuting] = useState(false)
  const [execError, setExecError] = useState<string | null>(null)

  const [tickets, setTickets] = useState<Ticket[] | null>(null)
  const [creatingTickets, setCreatingTickets] = useState(false)
  const [ticketsError, setTicketsError] = useState<string | null>(null)

  const [messages, setMessages] = useState<WhatsAppMessage[] | null>(null)
  const [executingWhatsapp, setExecutingWhatsapp] = useState(false)
  const [whatsappError, setWhatsappError] = useState<string | null>(null)

  const [plan90Tickets, setPlan90Tickets] = useState<Ticket[] | null>(null)
  const [creatingPlan90, setCreatingPlan90] = useState(false)
  const [plan90Error, setPlan90Error] = useState<string | null>(null)

  const handleCreatePlan90Tickets = async () => {
    setCreatingPlan90(true)
    setPlan90Error(null)
    try {
      await api.executeMarketingPlan90(planId)
      const poll = async () => {
        const record = await api.getMarketingPlan90(planId)
        if (record.status === 'DONE') {
          setPlan90Tickets(record.tickets)
          setCreatingPlan90(false)
          return
        }
        if (record.status === 'FAILED') {
          setPlan90Error(record.error ?? 'Error al crear los tickets')
          setCreatingPlan90(false)
          return
        }
        setTimeout(poll, 5000)
      }
      poll()
    } catch (e: unknown) {
      setPlan90Error(e instanceof Error ? e.message : 'Error al crear los tickets')
      setCreatingPlan90(false)
    }
  }

  const handleExecuteWhatsapp = async () => {
    setExecutingWhatsapp(true)
    setWhatsappError(null)
    try {
      await api.executeMarketingWhatsapp(planId)
      const poll = async () => {
        const record = await api.getMarketingWhatsapp(planId)
        if (record.status === 'DONE') {
          setMessages(record.mensajes)
          setExecutingWhatsapp(false)
          return
        }
        if (record.status === 'FAILED') {
          setWhatsappError(record.error ?? 'Error al generar los mensajes')
          setExecutingWhatsapp(false)
          return
        }
        setTimeout(poll, 5000)
      }
      poll()
    } catch (e: unknown) {
      setWhatsappError(e instanceof Error ? e.message : 'Error al generar los mensajes')
      setExecutingWhatsapp(false)
    }
  }

  const handleCreateActionTickets = async () => {
    setCreatingTickets(true)
    setTicketsError(null)
    try {
      await api.executeMarketingActions(planId)
      const poll = async () => {
        const record = await api.getMarketingActions(planId)
        if (record.status === 'DONE') {
          setTickets(record.tickets)
          setCreatingTickets(false)
          return
        }
        if (record.status === 'FAILED') {
          setTicketsError(record.error ?? 'Error al crear los tickets')
          setCreatingTickets(false)
          return
        }
        setTimeout(poll, 5000)
      }
      poll()
    } catch (e: unknown) {
      setTicketsError(e instanceof Error ? e.message : 'Error al crear los tickets')
      setCreatingTickets(false)
    }
  }

  const handleExecuteContent = async () => {
    setExecuting(true)
    setExecError(null)
    try {
      await api.executeMarketingContent(planId)
      const poll = async () => {
        const record = await api.getMarketingContent(planId)
        if (record.status === 'DONE') {
          setPieces(record.pieces)
          setExecuting(false)
          return
        }
        if (record.status === 'FAILED') {
          setExecError(record.error ?? 'Error al generar el contenido')
          setExecuting(false)
          return
        }
        setTimeout(poll, 5000)
      }
      poll()
    } catch (e: unknown) {
      setExecError(e instanceof Error ? e.message : 'Error al generar el contenido')
      setExecuting(false)
    }
  }

  return (
    <div className="space-y-2">
      <Section title="1. Diagnóstico Inicial" defaultOpen>
        <BulletList items={plan.diagnostico_inicial} />
      </Section>

      <Section title="2. Estrategia de Adquisición">
        <BulletList items={plan.estrategia_adquisicion} />
      </Section>

      <Section title="3. Calendario de Contenido (30 días)">
        <div className="space-y-3">
          {plan.calendario_contenido.map((item, i) => (
            <div key={i} className="bg-surface border border-border rounded-lg p-3">
              <div className="flex items-center gap-2 mb-1.5">
                <span className="text-xs font-mono text-accent">Día {item.dia}</span>
                <span className="text-[10px] text-muted bg-s3 rounded px-1.5 py-0.5">{item.formato}</span>
                <span className="text-xs text-dim font-medium ml-1">{item.objetivo}</span>
              </div>
              <p className="text-sm text-dim mb-1.5">{item.guion}</p>
              <p className="text-xs text-muted italic">CTA: {item.cta}</p>
            </div>
          ))}

          <button
            className="btn-primary flex items-center gap-2 w-full justify-center"
            onClick={handleExecuteContent}
            disabled={executing}
          >
            {executing
              ? <><RefreshCw className="w-4 h-4 animate-spin" /> Generando contenido real…</>
              : <><Wand2 className="w-4 h-4" /> Generar contenido real</>}
          </button>

          {execError && (
            <div className="flex items-center gap-2 bg-danger/10 border border-danger/30 text-danger
                            text-sm rounded-lg px-4 py-3">
              <AlertTriangle className="w-4 h-4" /> {execError}
            </div>
          )}

          {pieces && (
            <div className="space-y-3 pt-1">
              {pieces.map((piece, i) => (
                <ContentPieceCard key={i} piece={piece} />
              ))}
            </div>
          )}
        </div>
      </Section>

      <Section title="4. Embudo de Ventas">
        <BulletList items={plan.embudo_ventas} />
      </Section>

      <Section title="5. Estrategia WhatsApp">
        <div className="space-y-3">
          <BulletList items={plan.estrategia_whatsapp} />

          <button
            className="btn-primary flex items-center gap-2 w-full justify-center"
            onClick={handleExecuteWhatsapp}
            disabled={executingWhatsapp}
          >
            {executingWhatsapp
              ? <><RefreshCw className="w-4 h-4 animate-spin" /> Generando mensajes reales…</>
              : <><Wand2 className="w-4 h-4" /> Generar mensajes reales</>}
          </button>

          {whatsappError && (
            <div className="flex items-center gap-2 bg-danger/10 border border-danger/30 text-danger
                            text-sm rounded-lg px-4 py-3">
              <AlertTriangle className="w-4 h-4" /> {whatsappError}
            </div>
          )}

          {messages && (
            <div className="space-y-3 pt-1">
              {messages.map((msg, i) => (
                <WhatsAppMessageCard key={i} message={msg} />
              ))}
            </div>
          )}
        </div>
      </Section>

      <Section title="6. Plan de Ejecución (90 días)">
        <div className="space-y-4">
          {plan90Tickets
            ? plan90Tickets.map((t) => <ActionTicketRow key={t.id} ticket={t} />)
            : ([
                ['Semana 1-2', plan.plan_ejecucion_90_dias.semana_1_2],
                ['Semana 3-4', plan.plan_ejecucion_90_dias.semana_3_4],
                ['Mes 2', plan.plan_ejecucion_90_dias.mes_2],
                ['Mes 3', plan.plan_ejecucion_90_dias.mes_3],
              ] as [string, string[]][]).map(([label, items]) => (
                <div key={label}>
                  <p className="text-[10px] text-muted font-mono uppercase tracking-wide mb-2">{label}</p>
                  <BulletList items={items} />
                </div>
              ))}

          {!plan90Tickets && (
            <button
              className="btn-primary flex items-center gap-2 w-full justify-center"
              onClick={handleCreatePlan90Tickets}
              disabled={creatingPlan90}
            >
              {creatingPlan90
                ? <><RefreshCw className="w-4 h-4 animate-spin" /> Creando tickets…</>
                : <><Megaphone className="w-4 h-4" /> Crear tickets de este plan</>}
            </button>
          )}

          {plan90Error && (
            <div className="flex items-center gap-2 bg-danger/10 border border-danger/30 text-danger
                            text-sm rounded-lg px-4 py-3">
              <AlertTriangle className="w-4 h-4" /> {plan90Error}
            </div>
          )}
        </div>
      </Section>

      <Section title="7. IA y Automatización">
        <BulletList items={plan.ia_automatizacion} />
      </Section>

      <Section title="8. Métricas Clave">
        <BulletList items={plan.metricas_clave} />
      </Section>

      <Section title="9. Top 10 Acciones Inmediatas" defaultOpen>
        <div className="space-y-3">
          {tickets
            ? tickets.map((t) => <ActionTicketRow key={t.id} ticket={t} />)
            : <BulletList items={plan.top_10_acciones} />}

          {!tickets && (
            <button
              className="btn-primary flex items-center gap-2 w-full justify-center"
              onClick={handleCreateActionTickets}
              disabled={creatingTickets}
            >
              {creatingTickets
                ? <><RefreshCw className="w-4 h-4 animate-spin" /> Creando tickets…</>
                : <><Megaphone className="w-4 h-4" /> Crear tickets de estas acciones</>}
            </button>
          )}

          {ticketsError && (
            <div className="flex items-center gap-2 bg-danger/10 border border-danger/30 text-danger
                            text-sm rounded-lg px-4 py-3">
              <AlertTriangle className="w-4 h-4" /> {ticketsError}
            </div>
          )}
        </div>
      </Section>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------
export default function MarketingPage() {
  const [projects, setProjects] = useState<ProjectSummary[]>([])

  const [siteUrl,   setSiteUrl]   = useState('https://demo.wprecover.cl')
  const [bizType,   setBizType]   = useState('tienda WooCommerce')
  const [city,      setCity]      = useState('Santiago')
  const [budget,    setBudget]    = useState<MonthlyBudget>('medio')
  const [plan,      setPlan]      = useState<WprecoverPlan>('growth')
  const [projectId, setProjectId] = useState<string>('')

  const [generating, setGenerating] = useState(false)
  const [error,       setError]     = useState<string | null>(null)
  const [result,      setResult]    = useState<MarketingPlanRecord | null>(null)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    api.listProjects().then(res => setProjects(res.projects)).catch(() => {})
  }, [])

  const handleProjectSelect = (id: string) => {
    setProjectId(id)
    const project = projects.find(p => p.id === id)
    if (project) {
      setSiteUrl(project.site_url)
      setPlan(project.plan as WprecoverPlan)
    }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    setError(null)
    setResult(null)
    try {
      const req: MarketingGenerateRequest = {
        site_url: siteUrl,
        business_type: bizType,
        city,
        monthly_budget: budget,
        plan,
        project_id: projectId || undefined,
      }
      const record = await api.generateMarketingPlan(req)
      setResult(record)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Error al generar el plan de marketing')
    } finally {
      setGenerating(false)
    }
  }

  const handleDownload = async () => {
    if (!result) return
    setDownloading(true)
    try {
      const blob = await api.downloadMarketingPDF(result.id)
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `marketing-plan-${result.id}.pdf`
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Error al descargar el PDF')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-semibold flex items-center gap-2">
            <Megaphone className="w-5 h-5 text-accent" /> Marketing OS
          </h1>
          <p className="text-dim text-sm mt-0.5">
            Plan de marketing personalizado en 9 módulos, generado con IA a partir del diagnóstico real del sitio.
          </p>
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 bg-danger/10 border border-danger/30 text-danger
                        text-sm rounded-lg px-4 py-3 mb-5">
          <AlertTriangle className="w-4 h-4" /> {error}
        </div>
      )}

      <div className="grid grid-cols-1 xl:grid-cols-[380px_1fr] gap-6">
        {/* Left: form */}
        <div className="card self-start">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-4 h-4 text-accent" />
            <h2 className="font-medium text-sm">Datos del Cliente</h2>
          </div>

          <div className="space-y-3 mb-4">
            <div>
              <label className="text-xs text-muted mb-1 block">Proyecto (opcional)</label>
              <select className="select" value={projectId} onChange={e => handleProjectSelect(e.target.value)}>
                <option value="">Sin proyecto asociado</option>
                {projects.map(p => (
                  <option key={p.id} value={p.id}>{p.client_name} — {p.site_url}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="text-xs text-muted mb-1 block">URL del sitio</label>
              <input className="input" value={siteUrl}
                onChange={e => setSiteUrl(e.target.value)}
                placeholder="https://tusitio.cl" />
            </div>
            <div>
              <label className="text-xs text-muted mb-1 block">Rubro / tipo de negocio</label>
              <input className="input" value={bizType}
                onChange={e => setBizType(e.target.value)}
                placeholder="tienda WooCommerce / servicios / otro" />
            </div>
            <div>
              <label className="text-xs text-muted mb-1 block">Ciudad</label>
              <input className="input" value={city}
                onChange={e => setCity(e.target.value)}
                placeholder="Santiago" />
            </div>
            <div>
              <label className="text-xs text-muted mb-1 block">Presupuesto mensual</label>
              <select className="select" value={budget} onChange={e => setBudget(e.target.value as MonthlyBudget)}>
                {Object.entries(BUDGET_LABELS).map(([v, l]) => (
                  <option key={v} value={v}>{l}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="text-xs text-muted mb-1 block">Paquete WPRecover</label>
              <select className="select" value={plan} onChange={e => setPlan(e.target.value as WprecoverPlan)}>
                {Object.entries(PLAN_LABELS).map(([v, l]) => (
                  <option key={v} value={v}>{l}</option>
                ))}
              </select>
            </div>
          </div>

          <button
            className="btn-primary flex items-center gap-2 w-full justify-center"
            onClick={handleGenerate}
            disabled={generating || !siteUrl}
          >
            {generating
              ? <><RefreshCw className="w-4 h-4 animate-spin" /> Auditando sitio y consultando Claude…</>
              : <><Sparkles className="w-4 h-4" /> Generar Plan de Marketing</>}
          </button>
        </div>

        {/* Right: result */}
        <div className="space-y-4">
          {result && (
            <>
              <div className="card flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-[#e2e8f0]">Plan generado</p>
                  <p className="text-xs text-muted mt-0.5">
                    {result.request.site_url} · Recovery Score:{' '}
                    {result.recovery_score != null ? result.recovery_score.toFixed(1) : 'N/A'} ·{' '}
                    {result.created_at.slice(0, 16).replace('T', ' ')}
                  </p>
                </div>
                <button
                  className="btn-ghost border border-border flex items-center gap-2"
                  onClick={handleDownload}
                  disabled={downloading || !result.pdf_available}
                  title={!result.pdf_available ? 'PDF no disponible' : undefined}
                >
                  {downloading
                    ? <RefreshCw className="w-4 h-4 animate-spin" />
                    : <Download className="w-4 h-4" />}
                  Descargar PDF
                </button>
              </div>

              <PlanSections plan={result.plan} planId={result.id} />
            </>
          )}

          {!result && !generating && (
            <div className="flex flex-col items-center py-16 gap-3 text-center">
              <Inbox className="w-8 h-8 text-muted" />
              <p className="text-dim text-sm">Sin plan generado todavía.</p>
              <p className="text-xs text-muted">Completa el formulario y genera el plan de marketing.</p>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
